@URL = http://{{HOST}}:{{PORT}}/setup/credentials

### Add Credentials to Database

POST {{URL}}/add HTTP/1.1
x-secret-pass: {{SECRET}}
content-type: application/json

{
    "alias": "testing",
    "client_id": "testing123455667@google.com",
    "client_secret": "asdasdmladkasdjsadlaskjdaskdjadslasldjasda",
    "email": "test@testing.com",
    "redirect_uri": "https://testing.com"
}


### Get Credentials from Database

POST {{URL}}/get HTTP/1.1
x-secret-pass: {{SECRET}}

### Reset Credentials in the Database

DELETE {{URL}}/reset HTTP/1.1
x-secret-pass: {{SECRET}}