@URL = http://{{HOST}}:{{PORT}}/setup/credentials

### Add Credentials to Database

POST {{URL}}/add HTTP/1.1
x-secret-pass: {{SECRET}}
content-type: application/json

< ../../request-bodies/setup/credentials/add.json


### Get Credentials from Database

POST {{URL}}/get HTTP/1.1
x-secret-pass: {{SECRET}}


### Reset Credentials in the Database

DELETE {{URL}}/reset HTTP/1.1
x-secret-pass: {{SECRET}}