@URL = http://{{HOST}}:{{PORT}}/setup/scopes

### Add Scope to Database

POST {{URL}}/add HTTP/1.1
x-secret-pass: {{SECRET}}
content-type: application/json

< ../../request-bodies/setup/scope/add.json


### Get Scopes from Database

POST {{URL}}/get HTTP/1.1
x-secret-pass: {{SECRET}}


### Reset Scope in the Database

DELETE {{URL}}/reset HTTP/1.1
x-secret-pass: {{SECRET}}